export const photographyreviews = [
  {
    name: "Deepa Gangavathikar",
    booking: "Booked Photography Services",
    date: "12 Jan 2024",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/women/85.jpg",
    indicators: {
      Creativity: true,
      Professionalism: true,
      Quality: true,
      Punctuality: true,
      Behaviour: true,
      Communication: true,
    },
    text: "Photographer Pavan did a wonderful job covering our event. Very patient, creative, and very professional. The pictures turned out amazing — vibrant, candid, and full of life! Highly recommend their work 👍",
  },
  {
    name: "Sheareen Fatima",
    booking: "Booked Photography & Decor for Birthday",
    date: "4 Mar 2024",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    indicators: {
      Creativity: true,
      Professionalism: true,
      Quality: true,
      Punctuality: true,
      Behaviour: true,
      Communication: true,
    },
    text: "Overall good experience. Decor and photography was good, they were very punctual about time and specially photographers were very polite and professional. Made my son's 1st b'day very memorable. Thank you Hora Team!",
  },
  {
    name: "Vikas Yadav",
    booking: "Booked Photography Service",
    date: "28 Feb 2024",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/men/51.jpg",
    indicators: {
      Creativity: true,
      Professionalism: true,
      Quality: true,
      Punctuality: true,
      Behaviour: true,
      Communication: true,
    },
    text: "Services provided by Hora have been amazing. The photographer allotted by them was extremely professional and polite. Charges are also very affordable. Overall it was a great experience. Highly recommend.",
  },
  {
    name: "Sathya BPR",
    booking: "Booked Baby Photoshoot Service",
    date: "19 Apr 2024",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/women/56.jpg",
    indicators: {
      Creativity: true,
      Professionalism: true,
      Quality: true,
      Punctuality: true,
      Behaviour: true,
      Communication: true,
    },
    text: "Very good service! The photographer Gaja is so professional, decent and his clicks are awesome — especially my baby's pics. Thank you so much HORA!",
  },
  {
    name: "Umesh K",
    booking: "Booked Photography Services",
    date: "10 May 2024",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/men/61.jpg",
    indicators: {
      Creativity: true,
      Professionalism: true,
      Quality: true,
      Punctuality: true,
      Behaviour: true,
      Communication: true,
    },
    text: "The Best Services! Especially the photographer Mr. Devendra — such a down-to-earth, friendly and professional man. I was so happy about his services and behaviour! If you wanna try... close your eyes and book them! Highly recommend!",
  },
  {
    name: "Prathyusha Narakurthi",
    booking: "Booked Event Photography",
    date: "6 Jun 2024",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/women/71.jpg",
    indicators: {
      Creativity: true,
      Professionalism: true,
      Quality: true,
      Punctuality: true,
      Behaviour: true,
      Communication: true,
    },
    text: "I have utilised photography services from Hora. Vishnu, our photographer, made our occasion perfectly captured. He is punctual, professional and very accommodating. Booking with Hora was easy, and I would love to recommend them.",
  },
];
