export const photoCat = [
  {
    id: "1",
    image: "https://horaservices.com/api/uploads/compressed_webp/Birthday-Photography.webp",
    name: "Birthday-Photography",
    subCategory: "Birthday-Photography",
    catValue: "Birthday-Photography",
    imgAlt: "Birthday Photography ideas and packages",
  },
   {
    id: "2",
    image: "https://horaservices.com/api/uploads/compressed_webp/Anniversary-Photography.webp",
    name: "Anniversary Photography",
    subCategory: "Anniversary-Photography",
    catValue: "Anniversary-Photography",
    imgAlt: "Romantic anniversary couple shoot ideas",
  },
  {
    id: "3",
    image: "https://horaservices.com/api/uploads/compressed_webp/House-warming-Photography.webp",
    name: "House Warming Photography",
    subCategory: "House-Warming-Photography",
    catValue: "House-Warming-Photography",
    imgAlt: "New home photography and decoration shoots",
  },
   {
    id: "4",
    image: "https://horaservices.com/api/uploads/compressed_webp/Naming-ceremony-Photography.webp",
    name: "Naming Ceremony Photography",
    subCategory: "Naming-Ceremony-Photography",
    catValue: "Naming-Ceremony-Photography",
    imgAlt: "Naming ceremony and baby rituals photography",
  },
   {
    id: "5",
    image: "https://horaservices.com/api/uploads/compressed_webp/Bachelorette-Photography.webp",
    name: "Bachelorette Photography",
    subCategory: "Bachelorette-Photography",
    catValue: "Bachelorette-Photography",
    imgAlt: "Fun bachelorette party photoshoot ideas",
  },
  {
    id: "6",
    image: "https://horaservices.com/api/uploads/compressed_webp/Baby-Shower-Photography.webp",
    name: "Baby Shower Photography",
    subCategory: "Baby-Shower-Photography",
    catValue: "Baby-Shower-Photography",
    imgAlt: "Baby shower and family photoshoot ideas",
  },
  {
    id: "7",
    image: "https://horaservices.com/api/uploads/compressed_webp/Wedding-Photography.webp",
    name: "Wedding Photography",
    subCategory: "Wedding-Photography",
    catValue: "Wedding-Photography",
    imgAlt: "Wedding photography with cinematic shots",
  },
  {
    id: "8",
    image: "https://horaservices.com/api/uploads/compressed_webp/Engagement-Photography.webp",
    name: "Engagement Photography",
    subCategory: "Engagement-Photography",
    catValue: "Engagement-Photography",
    imgAlt: "Engagement photoshoots and pre-wedding moments",
  },
  {
    id: "9",
    image: "https://horaservices.com/api/uploads/compressed_webp/Maternity-Photography.webp",
    name: "Maternity Photography",
    subCategory: "Maternity-Photography",
    catValue: "Maternity-Photography",
    imgAlt: "Maternity photoshoot themes and poses",
  },
  
  {
    id: "10",
    image: "https://horaservices.com/api/uploads/compressed_webp/New-Born-Baby-Photography.webp",
    name: "New Born Baby Photography",
    subCategory: "New-Born-Baby-Photography",
    catValue: "New-Born-Baby-Photography",
    imgAlt: "Cute newborn photoshoot ideas",
  },
 
  
 
];
