export const venueReviews = [
  {
    name: "Priya Mehta",
    booking: "Booked Venue for Wedding Reception",
    date: "15 Feb 24",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    indicators: {
      Ambience: true,
      Behaviour: true,
      Food: true,
      Parking: true,
      Cleanliness: true,
      Punctuality: true,
    },
    text: "What a delightful experience we had! I'm so grateful for sending me the best Chef Vipin Kumar Arya who was so so experienced and skilled and dedicated...we had a party of 25 people and he made it so easy for me and all my family members to enjoy the party without any worries.",
  },
  {
    name: "Amit Srivastava",
    booking: "Booked Venue for Birthday Celebration",
    date: "03 Mar 24",
    rating: 4,
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    indicators: {
      Ambience: true,
      Behaviour: true,
      Food: true,
      Parking: false,
      Cleanliness: true,
      Punctuality: true,
    },
    text: "The hall was beautifully decorated and the staff was very cooperative. Food quality was excellent — especially the starters. Only concern was parking space which was a little tight. Overall a great experience and would definitely book again!",
  },
  {
    name: "Sunita Rao",
    booking: "Booked Venue for Anniversary Dinner",
    date: "20 April 24",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    indicators: {
      Ambience: true,
      Behaviour: true,
      Food: true,
      Parking: true,
      Cleanliness: true,
      Punctuality: true,
    },
    text: "Absolutely loved the ambience! The lighting, decor, and overall setup made our anniversary truly memorable. The team went above and beyond to make sure everything was perfect. The food was delicious and served hot. Highly recommended!",
  },
  {
    name: "Deepak Verma",
    booking: "Booked Venue for Corporate Event",
    date: "11 May 24",
    rating: 4,
    avatar: "https://randomuser.me/api/portraits/men/54.jpg",
    indicators: {
      Ambience: true,
      Behaviour: true,
      Food: false,
      Parking: true,
      Cleanliness: true,
      Punctuality: true,
    },
    text: "Very professional setup for our corporate gathering of 60+ people. The AV equipment was good, seating arrangement was comfortable and the staff was attentive throughout. Food could have been better but the overall experience was smooth and well managed.",
  },
  {
    name: "Kavya Nair",
    booking: "Booked Venue for Engagement Ceremony",
    date: "29 June 24",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/women/26.jpg",
    indicators: {
      Ambience: true,
      Behaviour: true,
      Food: true,
      Parking: true,
      Cleanliness: true,
      Punctuality: true,
    },
    text: "We hosted our engagement here and it was beyond perfect. The venue coordinator was extremely helpful right from the planning stage. The floral decor was fresh, the food was lip-smacking and all our guests kept complimenting the venue. 10/10 would recommend!",
  },
  {
    name: "Rahul Pandey",
    booking: "Booked Venue for Kids Birthday Party",
    date: "14 July 24",
    rating: 3,
    avatar: "https://randomuser.me/api/portraits/men/17.jpg",
    indicators: {
      Ambience: true,
      Behaviour: true,
      Food: false,
      Parking: false,
      Cleanliness: false,
      Punctuality: true,
    },
    text: "Decent venue for a small gathering. The kids enjoyed the space and the decoration team did a good job. However, the food quality was average and cleanliness in the washrooms could be improved. Staff was polite and responsive though. Average experience overall.",
  },
  {
    name: "Neha Joshi",
    booking: "Booked Venue for Baby Shower",
    date: "02 Aug 24",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    indicators: {
      Ambience: true,
      Behaviour: true,
      Food: true,
      Parking: true,
      Cleanliness: true,
      Punctuality: true,
    },
    text: "Had an amazing baby shower here! The team took care of every small detail — from the pastel decor theme to customized menu. The manager personally checked in multiple times to ensure everything was going well. Guests were very impressed. Will definitely come back for future events!",
  },
];