import veneue from "@/assets/venue.jpeg";

export const BIG_PITCHER_FOOD_PACKAGES = [
  {
    id: 1,
    name: "BASIC",
    price: "₹1,299/-",
    tag: "All Inclusive",
    image: veneue,
    includes: {
      appetisers: {
        veg: [
          "Hara Bhara Kebab",
          "Paneer Aloo Ki Tikki",
          "Zaitoon Paneer Tikka",
          "Hariyali Paneer Tikka",
          "Paneer Ke Sholey",
          "Multani Paneer Tikka",
          "Classic Paneer Tikka (Red)",
          "Potato And Peas Kurkure",
          "Wok Tossed Cauliflower",
          "Honey Chilli Potato",
          "Indo Chinese Paneer",
          "Baby Corn",
          "Crispy Chilli American Corn",
          "Veg Spring Rolls",
          "Veggie Bullets",
          "Jalapeno Cheese Balls",
          "French Fries",
          "Potato Basket",
          "In House Nachos",
          "Veg Nuggets",
          "Farmers Veg Pizza",
          "Paneer Ghee Roast, Pepper Dry",
          "Mushroom Pallipalayam",
          "Vegetable Cutlet",
          "Beetroot Cutlet",
        ],
        nonVeg: [
          "Hariyali Murgh Tikka",
          "Tandoori Murgh Banjara",
          "Lasooni Murgh Tikka",
          "Afghani Murgh Tikka",
          "Achari Murgh Tikka",
          "Murgh Malai Tikka",
          "Fish Koliwada",
          "Fish Tikka",
          "Thai Pai Chicken",
          "Indo Chinese Chilli Chicken",
          "Chicken Spring Roll",
          "Wings On Fire",
          "Spicy Coriander Chilli Chicken",
          "Indo Chinese Chilli Fish",
          "Chilli Coriander Fish",
          "Caribbean Fish Finger",
          "Peri Peri Chicken Wings",
          "Fisherman Fitters",
          "BBQ Chicken Wings",
          "Herb Crusted Chicken Pizza",
          "Chicken Ghee Roast",
          "Pallipalayam Chicken",
          "Malnad Pepper Chicken",
        ],
        note: "Choose any 3 Veg & 3 Non-Veg Starters",
      },
      mainCourse: {
        items: [
          "Methi Ka Khas Subzi",
          "Paneer Mirch Masala",
          "Paneer Khurchan",
          "Kadai Paneer",
          "Paneer Do Pyaza",
          "Paneer Makhanwala",
          "Dal Makhani",
          "Dal Fry",
          "Veg Biryani",
          "Chicken Butter Masala",
          "Murgh Do Pyaza",
          "Peshawar Kadai Murgh",
          "Chicken Kolhapuri",
          "Chicken Biryani",
          "Roti, Naan, Kulcha",
        ],
        note: "Choose any 2 Veg & 2 Non-Veg Main Course",
      },
      beverage: [
        "1 Freshly Brewed Craft Beer OR 1 Mocktail",
      ],
      desserts: ["2 Desserts from menu"],
      salads: ["2 Salads from menu"],
      note: "Excluding taxes",
    },
  },

  {
    id: 2,
    name: "ELITE",
    price: "₹1,699/-",
    tag: "All Inclusive",
    image: veneue,
    includes: {
      appetisers: {
        veg: [
          "Hara Bhara Kebab",
          "Paneer Aloo Ki Tikki",
          "Zaitoon Paneer Tikka",
          "Hariyali Paneer Tikka",
          "Paneer Ke Sholey",
          "Multani Paneer Tikka",
          "Classic Paneer Tikka (Red)",
          "Potato And Peas Kurkure",
          "Wok Tossed Cauliflower",
          "Honey Chilli Potato",
          "Indo Chinese Paneer",
          "Baby Corn",
          "Crispy Chilli American Corn",
          "Veg Spring Rolls",
          "Veggie Bullets",
          "Jalapeno Cheese Balls",
          "French Fries",
          "Potato Basket",
          "In House Nachos",
          "Veg Nuggets",
          "Farmers Veg Pizza",
          "Paneer Ghee Roast, Pepper Dry",
          "Mushroom Pallipalayam",
          "Vegetable Cutlet",
          "Beetroot Cutlet",
        ],
        nonVeg: [
          "Hariyali Murgh Tikka",
          "Tandoori Murgh Banjara",
          "Lasooni Murgh Tikka",
          "Afghani Murgh Tikka",
          "Achari Murgh Tikka",
          "Murgh Malai Tikka",
          "Fish Koliwada",
          "Fish Tikka",
          "Thai Pai Chicken",
          "Indo Chinese Chilli Chicken",
          "Chicken Spring Roll",
          "Wings On Fire",
          "Spicy Coriander Chilli Chicken",
          "Indo Chinese Chilli Fish",
          "Chilli Coriander Fish",
          "Caribbean Fish Finger",
          "Peri Peri Chicken Wings",
          "Fisherman Fitters",
          "BBQ Chicken Wings",
          "Herb Crusted Chicken Pizza",
          "Chicken Ghee Roast",
          "Pallipalayam Chicken",
          "Malnad Pepper Chicken",
        ],
        note: "Choose any 3 Veg & 3 Non-Veg Starters (served for 90 mins)",
      },
      mainCourse: {
        items: [
          "Methi Ka Khas Subzi",
          "Paneer Mirch Masala",
          "Paneer Khurchan",
          "Kadai Paneer",
          "Paneer Do Pyaza",
          "Paneer Makhanwala",
          "Dal Makhani",
          "Dal Fry",
          "Veg Biryani",
          "Chicken Butter Masala",
          "Murgh Do Pyaza",
          "Peshawar Kadai Murgh",
          "Chicken Kolhapuri",
          "Chicken Biryani",
          "Roti, Naan, Kulcha",
        ],
        note: "Choose any 2 Veg & 2 Non-Veg Main Course (served for 120 mins)",
      },
      beverage: [
        "Unlimited Freshly Brewed Craft Beer",
        "Unlimited Mocktails",
        "Bar service limited to 150 minutes",
      ],
      desserts: ["2 Desserts from menu"],
      salads: ["2 Salads from menu"],
      note: "Excluding taxes",
    },
  },

  {
    id: 3,
    name: "SUPREME",
    subtitle: "(IMFL)",
    price: "₹2,199/-",
    tag: "All Inclusive",
    image: veneue,
    includes: {
      appetisers: {
        veg: [
          "Hara Bhara Kebab",
          "Paneer Aloo Ki Tikki",
          "Zaitoon Paneer Tikka",
          "Hariyali Paneer Tikka",
          "Paneer Ke Sholey",
          "Multani Paneer Tikka",
          "Classic Paneer Tikka (Red)",
          "Potato And Peas Kurkure",
          "Wok Tossed Cauliflower",
          "Honey Chilli Potato",
          "Indo Chinese Paneer",
          "Baby Corn",
          "Crispy Chilli American Corn",
          "Veg Spring Rolls",
          "Veggie Bullets",
          "Jalapeno Cheese Balls",
          "French Fries",
          "Potato Basket",
          "In House Nachos",
          "Veg Nuggets",
          "Farmers Veg Pizza",
          "Paneer Ghee Roast, Pepper Dry",
          "Mushroom Pallipalayam",
          "Vegetable Cutlet",
          "Beetroot Cutlet",
        ],
        nonVeg: [
          "Hariyali Murgh Tikka",
          "Tandoori Murgh Banjara",
          "Lasooni Murgh Tikka",
          "Afghani Murgh Tikka",
          "Achari Murgh Tikka",
          "Murgh Malai Tikka",
          "Fish Koliwada",
          "Fish Tikka",
          "Thai Pai Chicken",
          "Indo Chinese Chilli Chicken",
          "Chicken Spring Roll",
          "Wings On Fire",
          "Spicy Coriander Chilli Chicken",
          "Indo Chinese Chilli Fish",
          "Chilli Coriander Fish",
          "Caribbean Fish Finger",
          "Peri Peri Chicken Wings",
          "Fisherman Fitters",
          "BBQ Chicken Wings",
          "Herb Crusted Chicken Pizza",
          "Chicken Ghee Roast",
          "Pallipalayam Chicken",
          "Malnad Pepper Chicken",
        ],
        note: "Choose any 3 Veg & 3 Non-Veg Starters (served for 90 mins)",
      },
      mainCourse: {
        items: [
          "Methi Ka Khas Subzi",
          "Paneer Mirch Masala",
          "Paneer Khurchan",
          "Kadai Paneer",
          "Paneer Do Pyaza",
          "Paneer Makhanwala",
          "Dal Makhani",
          "Dal Fry",
          "Veg Biryani",
          "Chicken Butter Masala",
          "Murgh Do Pyaza",
          "Peshawar Kadai Murgh",
          "Chicken Kolhapuri",
          "Chicken Biryani",
          "Roti, Naan, Kulcha",
        ],
        note: "Choose any 2 Veg & 2 Non-Veg Main Course (served for 120 mins)",
      },
      beverage: [
        "Unlimited Freshly Brewed Craft Beer",
        "Unlimited Mocktails",
        "Unlimited Cocktails",
        "IMFL — Black Dog 8 Years, Black & White, Roulette, Dewar's White Label, Morpheus XO, Blue Riband, Bacardi, Old Monk, Smirnoff, Wine",
        "Bar service limited to 150 minutes",
      ],
      desserts: ["3 Desserts from menu"],
      salads: ["2 Salads from menu"],
      note: "Excluding taxes",
    },
  },

  {
    id: 4,
    name: "SIGNATURE",
    subtitle: "(Imported Liquor)",
    price: "₹3,199/-",
    tag: "All Inclusive",
    image: veneue,
    includes: {
      appetisers: {
        veg: [
          "Hara Bhara Kebab",
          "Paneer Aloo Ki Tikki",
          "Zaitoon Paneer Tikka",
          "Hariyali Paneer Tikka",
          "Paneer Ke Sholey",
          "Multani Paneer Tikka",
          "Classic Paneer Tikka (Red)",
          "Potato And Peas Kurkure",
          "Wok Tossed Cauliflower",
          "Honey Chilli Potato",
          "Indo Chinese Paneer",
          "Baby Corn",
          "Crispy Chilli American Corn",
          "Veg Spring Rolls",
          "Veggie Bullets",
          "Jalapeno Cheese Balls",
          "French Fries",
          "Potato Basket",
          "In House Nachos",
          "Veg Nuggets",
          "Farmers Veg Pizza",
          "Paneer Ghee Roast, Pepper Dry",
          "Mushroom Pallipalayam",
          "Vegetable Cutlet",
          "Beetroot Cutlet",
        ],
        nonVeg: [
          "Hariyali Murgh Tikka",
          "Tandoori Murgh Banjara",
          "Lasooni Murgh Tikka",
          "Afghani Murgh Tikka",
          "Achari Murgh Tikka",
          "Murgh Malai Tikka",
          "Fish Koliwada",
          "Fish Tikka",
          "Thai Pai Chicken",
          "Indo Chinese Chilli Chicken",
          "Chicken Spring Roll",
          "Wings On Fire",
          "Spicy Coriander Chilli Chicken",
          "Indo Chinese Chilli Fish",
          "Chilli Coriander Fish",
          "Caribbean Fish Finger",
          "Peri Peri Chicken Wings",
          "Fisherman Fitters",
          "BBQ Chicken Wings",
          "Herb Crusted Chicken Pizza",
          "Chicken Ghee Roast",
          "Pallipalayam Chicken",
          "Malnad Pepper Chicken",
        ],
        note: "Choose any 4 Veg & 4 Non-Veg Starters (served for 90 mins)",
      },
      mainCourse: {
        items: [
          "Methi Ka Khas Subzi",
          "Paneer Mirch Masala",
          "Paneer Khurchan",
          "Kadai Paneer",
          "Paneer Do Pyaza",
          "Paneer Makhanwala",
          "Dal Makhani",
          "Dal Fry",
          "Veg Biryani",
          "Chicken Butter Masala",
          "Murgh Do Pyaza",
          "Peshawar Kadai Murgh",
          "Chicken Kolhapuri",
          "Chicken Biryani",
          "Roti, Naan, Kulcha",
        ],
        note: "Choose any 3 Veg & 3 Non-Veg Main Course (served for 120 mins)",
      },
      beverage: [
        "Unlimited Freshly Brewed Craft Beer",
        "Unlimited Mocktails",
        "Unlimited Cocktails",
        "Imported Liquor — J.W. Red Label, Jameson, Ballantines Fine, Jim Beam, Morpheus XO, Bombay Sapphire, Bacardi, Old Monk, Smirnoff, Absolut, Wines",
        "Bar service limited to 150 minutes",
      ],
      desserts: ["3 Desserts from menu"],
      salads: ["2 Salads from menu"],
      note: "Excluding taxes",
    },
  },

  {
    id: 5,
    name: "PREMIUM",
    subtitle: "(Premium Imported Liquor)",
    price: "₹4,199/-",
    tag: "All Inclusive",
    image: veneue,
    includes: {
      appetisers: {
        veg: [
          "Hara Bhara Kebab",
          "Paneer Aloo Ki Tikki",
          "Zaitoon Paneer Tikka",
          "Hariyali Paneer Tikka",
          "Paneer Ke Sholey",
          "Multani Paneer Tikka",
          "Classic Paneer Tikka (Red)",
          "Potato And Peas Kurkure",
          "Wok Tossed Cauliflower",
          "Honey Chilli Potato",
          "Indo Chinese Paneer",
          "Baby Corn",
          "Crispy Chilli American Corn",
          "Veg Spring Rolls",
          "Veggie Bullets",
          "Jalapeno Cheese Balls",
          "French Fries",
          "Potato Basket",
          "In House Nachos",
          "Veg Nuggets",
          "Farmers Veg Pizza",
          "Paneer Ghee Roast, Pepper Dry",
          "Mushroom Pallipalayam",
          "Vegetable Cutlet",
          "Beetroot Cutlet",
        ],
        nonVeg: [
          "Hariyali Murgh Tikka",
          "Tandoori Murgh Banjara",
          "Lasooni Murgh Tikka",
          "Afghani Murgh Tikka",
          "Achari Murgh Tikka",
          "Murgh Malai Tikka",
          "Fish Koliwada",
          "Fish Tikka",
          "Thai Pai Chicken",
          "Indo Chinese Chilli Chicken",
          "Chicken Spring Roll",
          "Wings On Fire",
          "Spicy Coriander Chilli Chicken",
          "Indo Chinese Chilli Fish",
          "Chilli Coriander Fish",
          "Caribbean Fish Finger",
          "Peri Peri Chicken Wings",
          "Fisherman Fitters",
          "BBQ Chicken Wings",
          "Herb Crusted Chicken Pizza",
          "Chicken Ghee Roast",
          "Pallipalayam Chicken",
          "Malnad Pepper Chicken",
        ],
        note: "Choose any 4 Veg & 4 Non-Veg Starters (served for 90 mins)",
      },
      mainCourse: {
        items: [
          "Methi Ka Khas Subzi",
          "Paneer Mirch Masala",
          "Paneer Khurchan",
          "Kadai Paneer",
          "Paneer Do Pyaza",
          "Paneer Makhanwala",
          "Dal Makhani",
          "Dal Fry",
          "Veg Biryani",
          "Chicken Butter Masala",
          "Murgh Do Pyaza",
          "Peshawar Kadai Murgh",
          "Chicken Kolhapuri",
          "Chicken Biryani",
          "Roti, Naan, Kulcha",
        ],
        note: "Choose any 3 Veg & 3 Non-Veg Main Course (served for 120 mins)",
      },
      beverage: [
        "Unlimited Freshly Brewed Craft Beer",
        "Unlimited Mocktails",
        "Unlimited Cocktails",
        "Premium Imported Liquor — Jack Daniel Black Label, Chivas, Glenfiddich, Morpheus XO, Bombay Sapphire, Bacardi, Old Monk, Grey Goose, Absolut, Wines",
        "Bar service limited to 150 minutes",
      ],
      desserts: ["3 Desserts from menu"],
      salads: ["2 Salads from menu"],
      addOns: [
        "Lamb — ₹350 Per Head",
        "Prawns — ₹450 Per Head",
      ],
      note: "Excluding taxes",
    },
  },
];
