import SLIVER from "@/assets/venueimages/silver.jpeg";
import GOLD from "@/assets/venueimages/Gold.png";
import PLATINUM from "@/assets/venueimages/non-veg.jpeg";
export const ROYAL_ORCHID_PACKAGES = [
  {
    id: 1,
    name: "SILVER MENU",
    subtitle:
      "1 Welcome Drink • 1 Veg Starter • 1 Non-Veg Starter • 2 Salads • 1 Veg Soup • 1 Paneer Main Course • 2 Veg Main Course • 2 Non-Veg Main Course (Fish & Chicken) • 1 Dal or Sambhar • 2 Assorted Indian Breads • 1 Flavoured Rice • Accompaniments • 2 Desserts • 1 Ice Cream",
    price: "₹2,380/-",
    tag: "Plus Taxes",
    type: "nveg",
    typeLabel: "Non-Veg",
    image: SLIVER,
    includes: {
      beverage: [
        "Welcome Drink",
      ],
      beverageNote: "Choose any 1 Welcome Drink",

      appetisers: {
        veg: [
          "Habhara Kebab",
          "Corn Tikki",
          "Aloo Tikki",
          "Tandoori Gobi",
          "Malai Tandoori Phool",
          "Paneer Tikka",
          "Lasooni Paneer",
          "Achari Paneer",
          "Malai Paneer",
          "Hariyali Paneer",
          "Veg Manchurian",
          "Honey Chilly Veg",
          "Chilli Paneer",
          "Paneer Manchurian",
          "Veg Spring Roll",
        ],
        nonVeg: [
          "Rawa Fried Fish",
          "Chilli Fish",
          "Fish Manchurian",
          "Fish Finger",
          "Achari Chicken Tikka",
          "Murgh Tikka",
          "Malai Murgh Tikka",
          "Hariyali Murgh Tikka",
          "Tandoori Chicken",
          "Chilli Chicken",
          "Chicken Manchurian",
          "Salt N Pepper Chicken",
        ],
        note: "Choose any 1 Veg + 1 Non-Veg Starter",
      },

      soups: [
        "Hot & Sour Soup",
        "Veg Clear Soup",
        "Sweet Corn Soup",
        "Tom Yum Soup",
        "Lemon & Coriander Soup",
        "Sweet Corn Veg Soup",
        "Spinach Burnt Garlic Soup",
        "Veg Manchow",
        "Lemon Pepper Soup",
        "Chinese Green Soup",
      ],
      soupsNote: "Choose any 1 Veg Soup",

      salads: [
        "Green Salad",
        "Tossed Salad",
        "Three Bean Salad",
        "American Corn Salad",
        "Russian Salad",
        "Coleslaw Hawaiian",
        "Pasta Salad",
        "Aloo Channa Chaat",
        "Sprouted Chaat",
        "Corn and Peas Chaat",
        "Moong Dal Kozambari",
        "Peanut Corn Kozambari",
      ],
      saladsNote: "Choose any 2 Salads",

      mainCourse: {
        veg: [
          "Kadai Paneer",
          "Paneer Makhani",
          "Achari Paneer",
          "Matar Paneer",
          "Paneer Lababdar",
          "Palak Paneer",
          "Malai Kofta",
          "Nizami Handi",
          "Aloo Gobi Adraki",
          "Corn Palak",
          "Corn Peas Masala",
          "Baby Corn Mushroom Masala",
          "Bhindi Do Pyaza",
          "Kadai Bhindi",
          "Aloo Mutter",
        ],
        nonVeg: [
          "Dhaba Murgh",
          "Kadai Murgh",
          "Murgh Makhani",
          "Butter Chicken",
          "Methi Murgh",
          "Chicken Tawa Masala",
          "Kozhi Chettinad",
          "Malabar Chicken Curry",
          "Goan Fish Curry",
          "Mangalorean Fish Curry",
          "Malabar Fish Curry",
          "Chettinad Fish Curry",
          "Kerala Fish Curry",
        ],
        note: "Choose 1 Paneer Main Course + 2 Veg Main Course + 2 Non-Veg Main Course (Fish & Chicken)",
      },

      dal: [
        "Sambar",
        "Andhra Tomato Pappu",
        "Dal Methi",
        "Dal Palak",
        "Dal Tadka",
        "Dal Makhani",
        "Ghar Ki Dal",
        "Dhaba Ki Dal",
        "Dal Amritsari",
        "Green Moong Dal",
        "Chenna Dal Tadka",
      ],
      dalNote: "Choose any 1 Dal or Sambhar",

      rice: [
        "Lemon Rice",
        "Tomato Rice",
        "Coconut Rice",
        "Bisibella Bath",
        "Veg Pulao",
        "Jeera Pulao",
        "Kaju Pulao",
        "Veg Dum Biryani",
        "Ghee Rice",
        "Veg Fried Rice",
        "Szechwan Fried Rice",
        "Burnt Garlic Fried Rice",
        "Veg Hakka Noodles",
      ],
      riceNote: "Choose any 1 Flavoured Rice",

      bread: [
        "Butter Roti",
        "Garlic Roti",
        "Pudina Roti",
        "Butter Naan",
        "Garlic Naan",
        "Pudina Naan",
      ],
      breadNote: "Choose any 2 Types of Assorted Indian Breads",

      accompaniments: [
        "Steamed Rice",
        "Pickle",
        "Papad",
        "Rasam",
        "Curd or Raita or Dahi Vada",
      ],

      desserts: [
        "Gajar Halwa",
        "Moong Dal Halwa",
        "Gulab Jamun",
        "Kala Jamun",
        "Dal Payasam",
        "Semiya Payasam",
        "Rice Kheer",
        "Shahi Tukda",
        "Mango Phirini",
        "Jalebi with Rabdi",
        "Mysore Pak",
        "Carrot Kheer",
        "Chocolate Mousse",
        "Caramel Custard",
        "Fruit Trifle",
      ],
      dessertsNote: "Choose any 2 Desserts",

      iceCream: [
        "Vanilla",
        "Strawberry",
        "Chocolate",
        "Mango",
        "Butter Scotch",
      ],
      iceCreamNote: "Choose any 1 Ice Cream",

      addOns: [],
      note: "Plus Taxes",
    },
  },

  {
    id: 2,
    name: "GOLD MENU",
    subtitle:
      "1 Welcome Drink • 2 Veg Starters • 2 Non-Veg Starters • 2 Salads • 1 Veg or Non-Veg Soup • 1 Paneer Main Course • 2 Veg Main Course • 2 Non-Veg Main Course (Fish & Chicken) • 1 Dal or Sambhar • 2 Assorted Indian Breads • 1 Flavoured Rice • Accompaniments • 2 Desserts • 1 Ice Cream • 1 Veg Live Counter",
    price: "₹2,640/-",
    tag: "Plus Taxes",
    type: "nvegdlx",
    typeLabel: "Non-Veg",
    image: GOLD,
    includes: {
      beverage: [
        "Welcome Drink",
      ],
      beverageNote: "Choose any 1 Welcome Drink",

      appetisers: {
        veg: [
          "Habhara Kebab",
          "Corn Tikki",
          "Aloo Tikki",
          "Tandoori Gobi",
          "Malai Tandoori Phool",
          "Paneer Tikka",
          "Lasooni Paneer",
          "Achari Paneer",
          "Malai Paneer",
          "Hariyali Paneer",
          "Veg Manchurian",
          "Honey Chilly Veg",
          "Chilli Paneer",
          "Paneer Manchurian",
          "Veg Spring Roll",
        ],
        nonVeg: [
          "Rawa Fried Fish",
          "Chilli Fish",
          "Fish Manchurian",
          "Fish Finger",
          "Achari Chicken Tikka",
          "Murgh Tikka",
          "Malai Murgh Tikka",
          "Hariyali Murgh Tikka",
          "Tandoori Chicken",
          "Chilli Chicken",
          "Chicken Manchurian",
          "Salt N Pepper Chicken",
        ],
        note: "Choose any 2 Veg + 2 Non-Veg Starters",
      },

      soups: {
        veg: [
          "Hot & Sour Soup",
          "Veg Clear Soup",
          "Sweet Corn Soup",
          "Tom Yum Soup",
          "Lemon & Coriander Soup",
          "Sweet Corn Veg Soup",
          "Spinach Burnt Garlic Soup",
          "Veg Manchow",
          "Lemon Pepper Soup",
        ],
        nonVeg: [
          "Sweet Corn Chicken Soup",
          "Hot & Sour Chicken Soup",
          "Chicken Lemon Coriander Soup",
          "Chicken Clear Soup",
          "Chicken Manchow Soup",
        ],
      },
      soupsNote: "Choose any 1 Soup (Veg or Non-Veg)",

      salads: [
        "Green Salad",
        "Tossed Salad",
        "Three Bean Salad",
        "American Corn Salad",
        "Russian Salad",
        "Coleslaw Hawaiian",
        "Pasta Salad",
        "Aloo Channa Chaat",
        "Sprouted Chaat",
        "Corn and Peas Chaat",
        "Moong Dal Kozambari",
        "Peanut Corn Kozambari",
      ],
      saladsNote: "Choose any 2 Salads",

      mainCourse: {
        veg: [
          "Kadai Paneer",
          "Paneer Makhani",
          "Achari Paneer",
          "Matar Paneer",
          "Paneer Lababdar",
          "Palak Paneer",
          "Malai Kofta",
          "Nizami Handi",
          "Aloo Gobi Adraki",
          "Corn Palak",
          "Corn Peas Masala",
          "Baby Corn Mushroom Masala",
          "Bhindi Do Pyaza",
          "Kadai Bhindi",
          "Aloo Mutter",
        ],
        nonVeg: [
          "Dhaba Murgh",
          "Kadai Murgh",
          "Murgh Makhani",
          "Butter Chicken",
          "Methi Murgh",
          "Chicken Tawa Masala",
          "Kozhi Chettinad",
          "Malabar Chicken Curry",
          "Goan Fish Curry",
          "Mangalorean Fish Curry",
          "Malabar Fish Curry",
          "Chettinad Fish Curry",
          "Kerala Fish Curry",
        ],
        note: "Choose 1 Paneer Main Course + 2 Veg Main Course + 2 Non-Veg Main Course (Fish & Chicken)",
      },

      dal: [
        "Sambar",
        "Andhra Tomato Pappu",
        "Dal Methi",
        "Dal Palak",
        "Dal Tadka",
        "Dal Makhani",
        "Ghar Ki Dal",
        "Dhaba Ki Dal",
        "Dal Amritsari",
        "Green Moong Dal",
        "Chenna Dal Tadka",
      ],
      dalNote: "Choose any 1 Dal or Sambhar",

      rice: [
        "Lemon Rice",
        "Tomato Rice",
        "Coconut Rice",
        "Bisibella Bath",
        "Veg Pulao",
        "Jeera Pulao",
        "Kaju Pulao",
        "Veg Dum Biryani",
        "Ghee Rice",
        "Veg Fried Rice",
        "Szechwan Fried Rice",
        "Burnt Garlic Fried Rice",
        "Veg Hakka Noodles",
      ],
      riceNote: "Choose any 1 Flavoured Rice",

      bread: [
        "Butter Roti",
        "Garlic Roti",
        "Pudina Roti",
        "Butter Naan",
        "Garlic Naan",
        "Pudina Naan",
      ],
      breadNote: "Choose any 2 Types of Assorted Indian Breads",

      accompaniments: [
        "Pickle",
        "Papad",
        "Rasam",
        "Steamed Rice",
        "Curd or Raita or Dahi Vada",
      ],

      desserts: [
        "Gajar Halwa",
        "Moong Dal Halwa",
        "Gulab Jamun",
        "Kala Jamun",
        "Dal Payasam",
        "Semiya Payasam",
        "Rice Kheer",
        "Shahi Tukda",
        "Mango Phirini",
        "Jalebi with Rabdi",
        "Mysore Pak",
        "Carrot Kheer",
        "Chocolate Mousse",
        "Caramel Custard",
        "Fruit Trifle",
      ],
      dessertsNote: "Choose any 2 Desserts",

      iceCream: [
        "Vanilla",
        "Strawberry",
        "Chocolate",
        "Mango",
        "Butter Scotch",
      ],
      iceCreamNote: "Choose any 1 Ice Cream",

      addOns: [
        "Live Counter (Any 1) — Veg @ ₹150/- per person (Dosa / Pav Bhaji / Bajji / Tatte Idli / Kothu Parotta)",
      ],
      note: "Plus Taxes",
    },
  },

  {
    id: 3,
    name: "PLATINUM MENU",
    subtitle:
      "1 Welcome Drink • 3 Veg Starters • 3 Non-Veg Starters • 3 Salads • 1 Veg Soup • 1 Non-Veg Soup • 1 Paneer Main Course • 2 Veg Main Course • 2 Non-Veg Main Course (Fish & Chicken) • 1 Dal or Sambhar • 2 Assorted Indian Breads • 1 Flavoured Rice • Accompaniments • 3 Desserts • 1 Ice Cream • 1 Veg Live Counter • 1 Non-Veg Live Counter (Fish or Chicken)",
    price: "₹3,100/-",
    tag: "Plus Taxes",
    type: "nvegdlx",
    typeLabel: "NV Deluxe",
    image: PLATINUM,
    includes: {
      beverage: [
        "Welcome Drink",
      ],
      beverageNote: "Choose any 1 Welcome Drink",

      appetisers: {
        veg: [
          "Habhara Kebab",
          "Corn Tikki",
          "Aloo Tikki",
          "Tandoori Gobi",
          "Malai Tandoori Phool",
          "Paneer Tikka",
          "Lasooni Paneer",
          "Achari Paneer",
          "Malai Paneer",
          "Hariyali Paneer",
          "Veg Manchurian",
          "Honey Chilly Veg",
          "Chilli Paneer",
          "Paneer Manchurian",
          "Veg Spring Roll",
        ],
        nonVeg: [
          "Rawa Fried Fish",
          "Chilli Fish",
          "Fish Manchurian",
          "Fish Finger",
          "Cajun Fried Fish",
          "Achari Chicken Tikka",
          "Murgh Tikka",
          "Malai Murgh Tikka",
          "Hariyali Murgh Tikka",
          "Tandoori Chicken",
          "Chilli Chicken",
          "Chicken Manchurian",
          "Salt N Pepper Chicken",
          "Kung Pao Chicken",
        ],
        note: "Choose any 3 Veg + 3 Non-Veg Starters",
      },

      soups: {
        veg: [
          "Hot & Sour Soup",
          "Veg Clear Soup",
          "Sweet Corn Soup",
          "Tom Yum Soup",
          "Lemon & Coriander Soup",
          "Sweet Corn Veg Soup",
          "Spinach Burnt Garlic Soup",
          "Veg Manchow",
          "Lemon Pepper Soup",
        ],
        nonVeg: [
          "Sweet Corn Chicken Soup",
          "Hot & Sour Chicken Soup",
          "Chicken Lemon Coriander Soup",
          "Chicken Clear Soup",
          "Chicken Manchow Soup",
        ],
      },
      soupsNote: "Choose any 1 Veg Soup + 1 Non-Veg Soup",

      salads: [
        "Green Salad",
        "Tossed Salad",
        "Three Bean Salad",
        "American Corn Salad",
        "Russian Salad",
        "Coleslaw Hawaiian",
        "Pasta Salad",
        "Kimchi Salad",
        "Aloo Channa Chaat",
        "Sprouted Chaat",
        "Corn and Peas Chaat",
        "Moong Dal Kozambari",
        "Peanut Corn Kozambari",
        "Coconut Sundal Salad",
      ],
      saladsNote: "Choose any 3 Salads",

      mainCourse: {
        veg: [
          "Kadai Paneer",
          "Paneer Makhani",
          "Achari Paneer",
          "Matar Paneer",
          "Paneer Lababdar",
          "Palak Paneer",
          "Malai Kofta",
          "Nizami Handi",
          "Aloo Gobi Adraki",
          "Corn Palak",
          "Corn Peas Masala",
          "Baby Corn Mushroom Masala",
          "Bhindi Do Pyaza",
          "Kadai Bhindi",
          "Aloo Mutter",
        ],
        nonVeg: [
          "Dhaba Murgh",
          "Kadai Murgh",
          "Murgh Makhani",
          "Butter Chicken",
          "Methi Murgh",
          "Chicken Tawa Masala",
          "Kozhi Chettinad",
          "Nilgiri Chicken Korma",
          "Malabar Chicken Curry",
          "Andhra Chicken Curry",
          "Goan Fish Curry",
          "Mangalorean Fish Curry",
          "Malabar Fish Curry",
          "Chettinad Fish Curry",
          "Kerala Fish Curry",
          "Aleppy Fish Curry",
        ],
        note: "Choose 1 Paneer Main Course + 2 Veg Main Course + 2 Non-Veg Main Course (Fish & Chicken)",
      },

      dal: [
        "Sambar",
        "Andhra Tomato Pappu",
        "Dal Methi",
        "Dal Palak",
        "Dal Tadka",
        "Dal Makhani",
        "Ghar Ki Dal",
        "Dhaba Ki Dal",
        "Dal Amritsari",
        "Green Moong Dal",
        "Chenna Dal Tadka",
        "Afgani Dal",
      ],
      dalNote: "Choose any 1 Dal or Sambhar",

      rice: [
        "Lemon Rice",
        "Tomato Rice",
        "Coconut Rice",
        "Bisibella Bath",
        "Veg Pulao",
        "Jeera Pulao",
        "Kaju Pulao",
        "Kashmir Pulao",
        "Veg Dum Biryani",
        "Ghee Rice",
        "Veg Fried Rice",
        "Szechwan Fried Rice",
        "Burnt Garlic Fried Rice",
        "Mushroom Fried Rice",
        "Veg Hakka Noodles",
        "Szechwan Noodles",
      ],
      riceNote: "Choose any 1 Flavoured Rice",

      bread: [
        "Butter Roti",
        "Garlic Roti",
        "Pudina Roti",
        "Butter Naan",
        "Garlic Naan",
        "Pudina Naan",
      ],
      breadNote: "Choose any 2 Types of Assorted Indian Breads",

      accompaniments: [
        "Pickle",
        "Papad",
        "Rasam",
        "Steamed Rice",
        "Curd or Raita or Dahi Vada",
      ],

      desserts: [
        "Gajar Halwa",
        "Moong Dal Halwa",
        "Gulab Jamun",
        "Kala Jamun",
        "Dal Payasam",
        "Tender Coconut Payasam",
        "Semiya Payasam",
        "Rice Kheer",
        "Shahi Tukda",
        "Mango Phirini",
        "Jalebi with Rabdi",
        "Mysore Pak",
        "Carrot Kheer",
        "Chocolate Mousse",
        "Caramel Custard",
        "Fruit Trifle",
        "Orange Soufflé",
        "Chocolate Soufflé",
        "Strawberry Soufflé",
      ],
      dessertsNote: "Choose any 3 Desserts",

      iceCream: [
        "Vanilla",
        "Strawberry",
        "Chocolate",
        "Mango",
        "Butter Scotch",
      ],
      iceCreamNote: "Choose any 1 Ice Cream",

      addOns: [
        "Veg Live Counter — ₹150/- per person (Dosa / Pav Bhaji / Appam / Kothu Parotta / Bajji)",
        "Non-Veg Live Counter — ₹250/- per person (Oil Fried Chicken / Tawa Fish / Chicken 65 / Pepper Chicken)",
      ],
      note: "Plus Taxes",
    },
  },
];