import veneue from "@/assets/venue.jpeg";
import foodIl from "@/assets/venueimages/foodil.jpeg"
import foodImfl from "@/assets/venueimages/foodimfl.jpeg"
import FoodPL from "@/assets/venueimages/FoodPL.jpeg"
export const STATIC_FOOD_PACKAGES = [
  {
    id: 1,
    name: "FOOD",
    subtitle:
      "3 Veg Starters • 3 Non-Veg Starters • 7 Main Course (Veg/Non-Veg) • Dessert • Ice Cream",
    price: "₹1,400/-",
    tag: "All Inclusive",
    image: veneue,
    includes: {
      beverage: [
        "Mocktails",
        "Canned Juices",
        "Water",
        "Coke, Sprite, Soda",
        "Tonic Water",
      ],
      beverageNote: "All beverages included",

      appetisers: {
        veg: [
          "French Paneer",
          "Mushroom Pepper",
          "Babycorn Chilli",
          "American Corn",
          "Hara Bhara Kabab",
          "Paneer Tikka",
        ],
        nonVeg: [
          "Chicken Kebab",
          "Chilli Chicken",
          "Fish Pepper",
          "Fish Koliwada",
          "Chicken Tikka",
          "Murgh Ke Sholay",
          "French Chicken",
        ],
        note: "Choose any 3 Veg + 3 Non-Veg Starters",
      },

      mainCourse: {
        items: [
          "Steamed Rice",
          "Jeera Rice",
          "Veg Biryani",
          "Veg Diwani Handi",
          "Chicken Biryani",
          "Dal Fry",
          "Paneer Butter Masala",
          "Chicken Butter Masala",
          "Dhingri Mutter",
          "Chicken Hyderabadi",
          "Tomato Kaju Masala",
          "Veg Noodles",
          "Chicken Noodles",
          "Assorted Roti - Naan, Tandoori, Kulcha",
        ],
        note: "Choose any 7",
      },

      desserts: ["Chocolate Brownie & Ice Cream"],
      dessertsNote: "Included",
    },
  },
  {
    id: 2,
    name: "FOOD & IMFL",
    subtitle: "3 Veg Starters • 3 Non-Veg Starters • 7 Main Course • Dessert | (Indian Made Foreign Liquor)",
    price: "₹1,600/-",
    tag: "All Inclusive",
    image: foodImfl,
    includes: {
      beverage: [
        "Whisky - Black Dog 8 years, Black & White",
        "Rum - Bacardi (White), Old Monk",
        "Vodka - Smirnoff",
        "Gin - Blue Riband / Greater Than",
        "Beer - Kingfisher Premium / Budweiser Premium Draught",
        "Cocktails & Mocktails",
        "Canned Juices",
        "Water",
        "Coke, Sprite, Soda",
        "Tonic Water",
      ],
      beverageNote: "2 Whisky • 2 Rum • 1 Vodka • 1 Gin • 1 Beer",
      appetisers: {
        veg: [
          "French Paneer",
          "Mushroom Pepper",
          "Babycorn Chili",
          "American Corn",
          "Hara Bhara Kabab",
          "Paneer Tikka",
        ],
        nonVeg: [
          "Chicken Kebab",
          "Chilly Chicken",
          "Fish Pepper",
          "Fish Koliwada",
          "Chicken Tikka",
          "Murgh Ke Sholay",
          "French Chicken",
        ],
        note: "Choose any 3 Veg + 3 Non-Veg Starters",
      },
      mainCourse: {
        items: [
          "Steamed Rice",
          "Jeera Rice",
          "Veg Biryani",
          "Veg Diwani Handi",
          "Chicken Biryani",
          "Dal Fry",
          "Paneer Butter Masala",
          "Chicken Butter Masala",
          "Dhingri Mutter",
          "Chicken Hyderabadi",
          "Tomato Kaju Masala",
          "Veg Noodles",
          "Chicken Noodles",
          "Assorted Roti - Naan, Tandoori, Kulcha",
        ],
        note: "Choose any 7",
      },
      desserts: ["Chocolate Brownie & Ice Cream"],
      dessertsNote: "Included",
    },
  },

  {
    id: 3,
    name: "FOOD & IL",
    subtitle: "3 Veg Starters • 3 Non-Veg Starters • 7 Main Course • Dessert | (Imported Liquor)",
    price: "₹3,500/-",
    tag: "All Inclusive",
    image: foodIl,
    includes: {
      beverage: [
        "Whisky - Jameson, Ballantine's, Jim Beam",
        "Rum - Bacardi (White), Old Monk",
        "Vodka - Absolut",
        "Gin - Beefeater, Bombay Sapphire",
        "Beer - Kingfisher Premium / Budweiser Premium Draught",
        "Cocktails & Mocktails",
        "Canned Juices",
        "Water",
        "Coke, Sprite, Soda",
        "Tonic Water",
      ],
      beverageNote: "3 Whisky • 2 Rum • 1 Vodka • 2 Gin • 1 Beer",
      appetisers: {
        veg: [
          "French Paneer",
          "Mushroom Pepper",
          "Babycorn Chili",
          "American Corn",
          "Hara Bhara Kabab",
          "Paneer Tikka",
        ],
        nonVeg: [
          "Chicken Kebab",
          "Chilly Chicken",
          "Fish Pepper",
          "Fish Koliwada",
          "Chicken Tikka",
          "Murgh Ke Sholay",
          "French Chicken",
        ],
        note: "Choose any 3 Veg + 3 Non-Veg Starters",
      },
      mainCourse: {
        items: [
          "Steamed Rice",
          "Jeera Rice",
          "Veg Biryani",
          "Veg Diwani Handi",
          "Chicken Biryani",
          "Dal Fry",
          "Paneer Butter Masala",
          "Chicken Butter Masala",
          "Dhingri Mutter",
          "Chicken Hyderabadi",
          "Tomato Kaju Masala",
          "Veg Noodles",
          "Chicken Noodles",
          "Assorted Roti - Naan, Tandoori, Kulcha",
        ],
        note: "Choose any 7",
      },
      desserts: ["Chocolate Brownie & Ice Cream"],
      dessertsNote: "Included",
    },
  },

  {
    id: 4,
    name: "FOOD & PL",
    subtitle: "3 Veg Starters • 3 Non-Veg Starters • 7 Main Course • Dessert | (Premium Liquor)",
    price: "₹4,500/-",
    tag: "All Inclusive",
    image: FoodPL,
    includes: {
      beverage: [
        "Whisky - Chivas 12 years, Jack Daniels, Black Label",
        "Rum - Bacardi (White), Old Monk",
        "Vodka - Grey Goose, Absolut",
        "Gin - Beefeater, Bombay Sapphire",
        "Beer - Kingfisher Premium / Budweiser Premium Draught",
        "Cocktails & Mocktails",
        "Canned Juices",
        "Water",
        "Coke, Sprite, Soda",
        "Tonic Water",
      ],
      beverageNote: "3 Whisky • 2 Rum • 2 Vodka • 2 Gin • 1 Beer",
      appetisers: {
        veg: [
          "French Paneer",
          "Mushroom Pepper",
          "Babycorn Chili",
          "American Corn",
          "Hara Bhara Kabab",
          "Paneer Tikka",
        ],
        nonVeg: [
          "Chicken Kebab",
          "Chilly Chicken",
          "Fish Pepper",
          "Fish Koliwada",
          "Chicken Tikka",
          "Murgh Ke Sholay",
          "French Chicken",
        ],
        note: "Choose any 3 Veg + 3 Non-Veg Starters",
      },
      mainCourse: {
        items: [
          "Steamed Rice",
          "Jeera Rice",
          "Veg Biryani",
          "Veg Diwani Handi",
          "Chicken Biryani",
          "Dal Fry",
          "Paneer Butter Masala",
          "Chicken Butter Masala",
          "Dhingri Mutter",
          "Chicken Hyderabadi",
          "Tomato Kaju Masala",
          "Veg Noodles",
          "Chicken Noodles",
          "Assorted Roti - Naan, Tandoori, Kulcha",
        ],
        note: "Choose any 7",
      },
      desserts: ["Chocolate Brownie & Ice Cream"],
      dessertsNote: "Included",
    },
  },
];
