import veneue from "@/assets/venue.jpeg";

export const STATIC_FOOD_PACKAGES = [
  {
    id: 1,
    name: "FOOD",
    price: "₹1,400/-",
    tag: "All Inclusive",
    image: veneue,
    includes: {
      appetisers: {
        veg: [
          "French Paneer",
          "American Corn",
          "Hara Bhara Kabab",
        ],
        nonVeg: [
          "Chicken Tukda Kebab",
          "Chilly Chicken",
          "Fish Pepper",
        ],
        note: "Choose any 3",
      },
      mainCourse: {
        items: [
          "Veg Biryani",
          "Chicken Biryani",
          "Dal Kichdi",
          "Chicken Butter Masala",
          "Tomato Kaju Masala",
          "Assorted Roti - Naan, Tandoori, Kulcha",
        ],
        note: "Choose any 5",
      },
      beverage: [
        "Mocktails",
        "Canned Juices",
        "Water",
        "Coke, Sprite, Soda",
        "Tonic Water",
      ],
      desserts: ["Gulab Jamoon & Ice Cream"],
    },
  },

  {
    id: 2,
    name: "FOOD & BEER",
    price: "₹1,600/-",
    tag: "All Inclusive",
    image: veneue,
    includes: {
      appetisers: {
        veg: [
          "French Paneer",
          "American Corn",
          "Hara Bhara Kabab",
        ],
        nonVeg: [
          "Chicken Tukda Kebab",
          "Chilly Chicken",
          "Fish Pepper",
        ],
        note: "Choose any 3",
      },
      mainCourse: {
        items: [
          "Veg Biryani",
          "Chicken Biryani",
          "Dal Kichdi",
          "Chicken Butter Masala",
          "Tomato Kaju Masala",
          "Assorted Roti - Naan, Tandoori, Kulcha",
        ],
        note: "Choose any 6",
      },
      beverage: [
        "Beer",
        "Mocktails",
        "Canned Juices",
        "Water",
        "Coke, Sprite, Soda",
        "Tonic Water",
      ],
      desserts: ["Gulab Jamoon & Ice Cream"],
    },
  },

  {
    id: 3,
    name: "FOOD & IMFL",
    subtitle: "(Indian Made Foreign Liquor)",
    price: "₹2,500/-",
    tag: "All Inclusive",
    image: veneue,
    includes: {
      appetisers: {
        veg: [
          "French Paneer",
          "Mushroom Pepper",
          "Babycorn Chili",
          "American Corn",
          "Hara Bhara Kabab",
          "Paneer Tikka",
        ],
        nonVeg: [
          "Chicken Kebab",
          "Chilly Chicken",
          "Fish Pepper",
          "Fish Koliwada",
          "Chicken Tikka",
          "Murgh Ke Sholay",
          "French Chicken",
        ],
        note: "Choose any 3",
      },
      mainCourse: {
        items: [
          "Steamed Rice",
          "Jeera Rice",
          "Veg Biryani",
          "Veg Diwani Handi",
          "Chicken Biryani",
          "Dal Fry",
          "Paneer Butter Masala",
          "Chicken Butter Masala",
          "Dhingri Mutter",
          "Chicken Hyderabadi",
          "Tomato Kaju Masala",
          "Veg Noodles",
          "Chicken Noodles",
          "Assorted Roti - Naan, Tandoori, Kulcha",
        ],
        note: "Choose any 7",
      },
      beverage: [
        "Whisky - Black Dog 8 years, Black & White",
        "Rum - Bacardi (White), Old Monk",
        "Vodka - Smirnoff",
        "Gin - Blue Riband / Greater Than",
        "Beer - Kingfisher Premium / Budweiser Premium Draught",
        "Cocktails & Mocktails",
        "Canned Juices",
        "Water",
        "Coke, Sprite, Soda",
        "Tonic Water",
      ],
      desserts: ["Chocolate Brownie & Ice Cream"],
    },
  },

  {
    id: 4,
    name: "FOOD & IL",
    subtitle: "(Imported Liquor)",
    price: "₹3,500/-",
    tag: "All Inclusive",
    image: veneue,
    includes: {
      appetisers: {
        veg: [
          "French Paneer",
          "Mushroom Pepper",
          "Babycorn Chili",
          "American Corn",
          "Hara Bhara Kabab",
          "Paneer Tikka",
        ],
        nonVeg: [
          "Chicken Kebab",
          "Chilly Chicken",
          "Fish Pepper",
          "Fish Koliwada",
          "Chicken Tikka",
          "Murgh Ke Sholay",
          "French Chicken",
        ],
        note: "Choose any 3",
      },
      mainCourse: {
        items: [
          "Steamed Rice",
          "Jeera Rice",
          "Veg Biryani",
          "Veg Diwani Handi",
          "Chicken Biryani",
          "Dal Fry",
          "Paneer Butter Masala",
          "Chicken Butter Masala",
          "Dhingri Mutter",
          "Chicken Hyderabadi",
          "Tomato Kaju Masala",
          "Veg Noodles",
          "Chicken Noodles",
          "Assorted Roti - Naan, Tandoori, Kulcha",
        ],
        note: "Choose any 7",
      },
      beverage: [
        "Whisky - Jameson, Ballantine's, Jim Beam",
        "Rum - Bacardi (White), Old Monk",
        "Vodka - Absolut",
        "Gin - Beefeater, Bombay Sapphire",
        "Beer - Kingfisher Premium / Budweiser Premium Draught",
        "Cocktails & Mocktails",
        "Canned Juices",
        "Water",
        "Coke, Sprite, Soda",
        "Tonic Water",
      ],
      desserts: ["Chocolate Brownie & Ice Cream"],
    },
  },

  {
    id: 5,
    name: "FOOD & PL",
    subtitle: "(Premium Liquor)",
    price: "₹4,500/-",
    tag: "All Inclusive",
    image: veneue,
    includes: {
      appetisers: {
        veg: [
          "French Paneer",
          "Mushroom Pepper",
          "Babycorn Chili",
          "American Corn",
          "Hara Bhara Kabab",
          "Paneer Tikka",
        ],
        nonVeg: [
          "Chicken Kebab",
          "Chilly Chicken",
          "Fish Pepper",
          "Fish Koliwada",
          "Chicken Tikka",
          "Murgh Ke Sholay",
          "French Chicken",
        ],
        note: "Choose any 3",
      },
      mainCourse: {
        items: [
          "Steamed Rice",
          "Jeera Rice",
          "Veg Biryani",
          "Veg Diwani Handi",
          "Chicken Biryani",
          "Dal Fry",
          "Paneer Butter Masala",
          "Chicken Butter Masala",
          "Dhingri Mutter",
          "Chicken Hyderabadi",
          "Tomato Kaju Masala",
          "Veg Noodles",
          "Chicken Noodles",
          "Assorted Roti - Naan, Tandoori, Kulcha",
        ],
        note: "Choose any 7",
      },
      beverage: [
        "Whisky - Chivas 12 years, Jack Daniels, Black Label",
        "Rum - Bacardi (White), Old Monk",
        "Vodka - Grey Goose, Absolut",
        "Gin - Beefeater, Bombay Sapphire",
        "Beer - Kingfisher Premium / Budweiser Premium Draught",
        "Cocktails & Mocktails",
        "Canned Juices",
        "Water",
        "Coke, Sprite, Soda",
        "Tonic Water",
      ],
      desserts: ["Chocolate Brownie & Ice Cream"],
    },
  },
];
